### ISSUE TITLE
Feature synchronization between API and API wrapper

### ISSUE THREAD

**Issue by jslegers** [sumocoders/Teamleader#21]
I'm currently working on a project intended to synchronize data between Drupal and Teamleader.

The main goal of this project is to provide live 2-way-synchronization between Drupal and Teamleader for company data and contact data. So any changes to company data or contact data in Drupal would automatically be imported into Teamleader and vice versa.

While I have considered writing my own library to communicate with the Teamleader API, I've decided to use this library instead for the time being, as this library seems to be have the official support of the Teamleader development team and I want to to ensure future compatibility with the Teamleader API.

My initial implementation allows me to create a contact in Teamleader whenever a user is added in Drupal and change a contact in Teamleader whenever a user is changed in Drupal.

Deletion of contacts was going to be the next feature to implement, but it appears that neither `https://www.teamleader.be/api/deleteCompany.php` nor `https://www.teamleader.be/api/deleteContact.php` have been implemented by this library (see also https://github.com/sumocoders/Teamleader/issues/22).
- Does either the SumoCoders dev team or Teamleader dev team have any plans to add these and/or other missing features to this wrapper library?
  - If yes, can you give an indication on when these features can be expected?
  - If not, would you accept any pull requests I make that contain missing features? And if you allow the addition of 3rd party code, do you have any coding standards I need to consider when adding the missing features to the library?

Finally, could you give me any idea on what I can expect regarding feature synchronization between this library and the Teamleader API in the future? Are features implemented by this library intended to stay synchronized with future versions of the Teamleader API whenever changes to the API are made?

**Comment by jslegers** [comment]
It seems that a fork for this project exists with more features than the master project.

That fork can be found at https://github.com/Restocheck/Teamleader and 

Additional features have been added by @ThomasMarcelis and @kidk.

* Which features have been added to that fork that are missing from the master repo?
* How stable is that fork?
* Why is it none of the features of this more recent fork have been merged with the master repo after about 2 months of inactivity?

**Comment by wdeeke** [comment]
No new significant pull requests have been received from this fork lately. We will check for major differences.

**Comment by jslegers** [comment]
@wdeeke :

Awesome!

I will use the official repo as a basis for my own development for the time being.

**Comment by kidk** [comment]
It seems we forgot about those changes, I will try to create a pull request in the coming weeks.

**Comment by carakas** [comment]
@kidk have those changes been PRed?
@jslegers is this still an issue? If so did you add things yourself that might be PRed or can we close this issue?

**Comment by kidk** [comment]
@carakas I don't think so. I no longer have access to this code. So I wont be able to help.

**Comment by jslegers** [comment]
@carakas :

As I said on the other issue : I moved on to different (not sure if they're greener) pastures.
