### ISSUE TITLE
Deleting CRM data

### ISSUE THREAD

**Issue by jslegers** [sumocoders/Teamleader#22]
It appears that neither `https://www.teamleader.be/api/deleteCompany.php` nor `https://www.teamleader.be/api/deleteContact.php` have been implemented by this library.

Do you have any plans to add these in the foreseeable future?
If not, would you accept pull requests with these missing features and which coding standards would I need to follow in that case?

For more details, see also https://github.com/sumocoders/Teamleader/issues/21.

**Comment by wdeeke** [comment]
Pull requests for these features will be accepted. If no new pull requests appear, Teamleader will add these soon.

**Comment by jslegers** [comment]
@wdeeke :

I'll keep you guys posted on my progress.

**Comment by jslegers** [comment]
@wdeeke :

I added a **crmDeleteContact** and **crmDeleteCompany** method to the Teamleader class.

A pull request for this addition be found at https://github.com/sumocoders/Teamleader/pull/23.
