### ISSUE TITLE
CURLOPT_FOLLOWLOCATION triggers error in case of open_basedir restriction

### ISSUE THREAD

**Issue by jslegers** [sumocoders/Teamleader#24]
Line 223 of file `Teamleader.php` contains the following cURL setting :

```php
$options[CURLOPT_FOLLOWLOCATION] = true;
```

In Belgium, Combell is a popular webhosting company for shared hosting environments and they have the open_basedir restriction enabled.

With the open_basedir restriction enabled, this setting generates a fatal error. That means, your library cannot be used on Combell servers or similar environments.

Removing or commenting this setting solves the error.

**Comment by WouterSioen** [comment]
The `ini_get('open_basedir')` method could be used to check if the open_basedir restriction is enabled.

**Comment by willemdelbare** [comment]
The Teamleader API currently does not use any header redirects and we are not planning to introduce this behaviour. I think it's safe to remove this line if it's causing trouble for some people.

**Comment by jslegers** [comment]
Why has this issue been closed? Judging by a quick look at [the code of Teamleader.php](https://github.com/sumocoders/Teamleader/blob/master/Teamleader.php), it doesn't appear to have been fixed!
