### ISSUE TITLE
Cant add company with KVK number (local business number)

### ISSUE THREAD

**Issue by Idotmedia** [sumocoders/Teamleader#45]
Hoi!

Wij proberen middels jullie code een API koppeling op te bouwen tussen Copernica en Teamleader. We krijgen een vreemde foutmelding zodra we een bedrijf proberen toe te voegen in teamleader wanneer we het veld "local business number" proberen te vullen. Zie onderstaande error (geedit om de klant anoniem te houden in deze);

Fatal error: Uncaught exception 'SumoCoders\Teamleader\Exception' with message 'Unknown method (setKvkNummer)' in /<link>/Teamleader/Crm/Company.php:639 Stack trace: #0 /<link>/Teamleader/Teamleader.php(684): SumoCoders\Teamleader\Crm\Company::initializeWithRawData(Array) #1 /<link>/sync/teamleaderlive.php(36): SumoCoders\Teamleader\Teamleader->crmGetCompany(5849706) #2 {main} thrown in /<link>/Teamleader/Crm/Company.php on line 639

Dingen die we reeds gedaan hebben:
- methode opgezocht waar die volgens de error zou moeten staan (is niet zo)
- de data die we versturen is daadwerkelijk een kvk nummer
- het bedrijf heeft ook een kvk nummer, en zo niet is dit geen probleem

De code lijkt hier onderuit te gaan: (lijn 36)
`$id = 5849706;//$data['object_id'];
  $companydata = $teamleader->crmGetCompany($id);`

Any clue? :-)

**Comment by turanct** [comment]
the library's codebase doesn't have the `setKvkNummer()` method for Companies, is this a default field in Teamleader? If so, you can just add a method for it and create a pull request here.
