### ISSUE TITLE
fetch extended contact details

### ISSUE THREAD

**Issue by Silassiai** [sumocoders/Teamleader#71]
Hi,

I don't know what i am doin wrong, but if i fetch the contacts, i get a minimum on contact details.
How do i retrieve extended details like, tags, description etc?
I only get this>>
```
$response = $teamleader->crmGetContacts();
array(12) {
  ["forename"]=>
  string(4) "Mark"
  ["surname"]=>
  string(7) "Summers"
  ["email"]=>
  string(22) "mark@summersdgtl.co.uk"
  ["country"]=>
  string(2) "GB"
  ["zipcode"]=>
  string(3) "B31"
  ["city"]=>
  string(10) "Birmingham"
  ["street"]=>
  string(17) "Westminster Road "
  ["number"]=>
  string(2) "20"
  ["language"]=>
  string(2) "EN"
  ["gender"]=>
  string(1) "M"
  ["dob"]=>
  int(348710400)
  ["gsm"]=>
  string(15) "+1 404-555-0137"
```

**Comment by StijnVrolijk** [comment]
@Silassiai If I'm correct the `crmGetContacts()` method is used to display an overview of contacts. To retrieve more information, try fetching a contact specifically with `crmGetContact($id)`.

So you could do this for example:
```
$contacts = $teamleader->crmGetContacts();

/** @var Contact */
for ($contacts as &$contact) {
    $contact = $teamleader->crmGetContact($contact->getId());
}
```

It's been a while since I've used this though so I could be wrong.

**Comment by Silassiai** [comment]
@StijnVrolijk thanks, now i get the results i want but it is all private.

Have you any idea how to fix that?

If i add the toArrayFor api it does not work.

`$contact->toArrayForApi();`

**Comment by StijnVrolijk** [comment]
@Silassiai There are getters for all properties. Take a look in [the Contact.php file](https://github.com/sumocoders/Teamleader/blob/master/Crm/Contact.php)

`toArrayForApi()` does exactly as described. It converts the `Contact` object to an array the API can use.

**Comment by Silassiai** [comment]
hmmm did something wrong. it works now, but can't add the 'status' to the toArrayForApi() method.
The getStatus returns NULL

```
public function toArrayForApi()
    {
        if ($this->getStatus()) {
// status is null in this case
            $return['status'] = $this->getStatus();
        }
```

**Comment by StijnVrolijk** [comment]
What exactly are you trying to accomplish?

**Comment by Silassiai** [comment]
and specialy this data that i am missing

```
 ["status"]=>
    string(8) "Hot lead"
    ["deleted"]=>
    int(0)
    ["newsletter"]=>
    int(1)
```

**Comment by Silassiai** [comment]
trying to add the getStatus() to the toArrayForApi, but results in NULL

**Comment by carakas** [comment]
then there is probably a bug in how the status is set and that bug should be fixed instead of this

**Comment by Silassiai** [comment]
@carakas sorry, i was just looking for a solution.
I found out the problem, the getContact.php does'nt return the 'status' which i found in the api documentation.

Maybe still a little ugly but i think this is the best solution for me?
This will gives me the most complete result.
[foreach ( $contacts as $key => $contact ) {
		$contact_details_1 = $contact->toArrayForApi();
		$contact           = $teamleader->crmGetContact( $contact->getId() );
		$contact_details_2 = $contact->toArrayForApi();
		$contact_full      = array_merge( $contact1, $contact2 );
	}
](url)

**Comment by carakas** [comment]
that is not really a scalable solution, so I wouldn't add this in the wrapper here, feel free to do so in your own application.

You can also always contact teamleader and ask for a way to request it from the api
