### ISSUE TITLE
Teamleader API v2

### ISSUE THREAD

**Issue by coreation** [sumocoders/Teamleader#74]
Hi there!

First and foremost, thank you for building and maintaining this API wrapper! 
Second, are there any plans to start/release a version of the PHP wrapper compatible with the v2 of Temleader's API?

**Comment by StijnVrolijk** [comment]
@coreation Hey!

We will probably update the wrapper once we need any of the v2 features, the v1 API gets disabled, someone else creates a PR or if someone pays us to do it ;)

**Comment by coreation** [comment]
:D I heard Teamleader is going to provide an PHP SDK themselves, ETA: "soon"... So perhaps let's wait until they're getting started

**Comment by carakas** [comment]
Was already aware of the fact that they would write their own wrapper for the next api. They already informed us about it.

closing this issue
