### ISSUE TITLE
The API key was not valid or the Teamleader account is no longer active.

### ISSUE THREAD

**Issue by jstam89** [sumocoders/Teamleader#87]
![image](https://user-images.githubusercontent.com/30374061/188313238-5552523b-20f5-433a-82e7-134a37e3c9f5.png)

I get the message The API key was not valid or the Teamleader account is no longer active.

Anyone can help me with this?

If I use the example as shown in this repo is says;

A department should have an id", exception: "InvalidArgumentException

Same as I request the contacts I get an error with a switch statement like below;

continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?"

Whatsup with this?

**Comment by dreadnip** [comment]
> continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?"

This is a common error when trying to run old PHP code with PHP >7.3. This package is not compatible. use [sumocoders/teamleader-oauth2](https://github.com/sumocoders/teamleader-oauth2) instead.
